### PR TITLE
new logo, and fix a few minor things

### PR DESCRIPTION
**Pull request by ervanalb**

### CODE REVIEW

**Comment by ervanalb** [comment]
also can you change the repo description to something else

**Comment by zbanks** [comment]
There's no tempo indicator on the effects when I build this branch locally. I'm assuming that's a bug because the files were deleted?
screenshot from 2018-10-07 16-16-39

**Comment by ervanalb** [comment]
try deleting all your *.qmlc files

**Comment by ervanalb** [comment]
do you know why the build failed? it seems to randomly fail

**Pull request merged**
